Repository Servnoww/Servnow-Spring, pull requests merged in 2024-08, with the labels that each got.

#18 [feat/#12] 설문작성 API 구현
  build.gradle
  src/main/java/servnow/servnow/api/question/service/MultipleChoiceUpdater.java
  src/main/java/servnow/servnow/api/question/service/QuestionUpdater.java
  src/main/java/servnow/servnow/api/section/service/SectionUpdater.java
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/request/SurveyPostRequest.java
  src/main/java/servnow/servnow/api/survey/service/SurveyCommandService.java
  src/main/java/servnow/servnow/api/survey/service/SurveyUpdater.java
  src/main/java/servnow/servnow/api/user/service/UserFinder.java
  src/main/java/servnow/servnow/api/user/service/UserInfoFinder.java
  src/main/java/servnow/servnow/common/code/UserErrorCode.java
  src/main/java/servnow/servnow/common/code/UserInfoErrorCode.java
  src/main/java/servnow/servnow/domain/question/model/MultipleChoice.java
  src/main/java/servnow/servnow/domain/question/model/Question.java
  src/main/java/servnow/servnow/domain/section/model/Section.java
  src/main/java/servnow/servnow/domain/survey/model/Survey.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
  src/main/java/servnow/servnow/domain/user/repository/UserInfoRepository.java
Labels: ✨ feat, 진

#19 [feat/#14] 설문조사 인트로 화면 API
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/response/SurveyIntroGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/common/code/SurveyErrorCode.java
  src/main/java/servnow/servnow/domain/common/BaseTimeEntity.java
  src/main/java/servnow/servnow/domain/section/model/Section.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 진

#21 [feat/#13] 설문조사 조회 화면 API (섹션별)
  src/main/java/servnow/servnow/api/section/service/SectionFinder.java
  src/main/java/servnow/servnow/api/section/service/SectionUpdater.java
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/request/SurveyPostRequest.java
  src/main/java/servnow/servnow/api/survey/dto/response/SurveyGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/common/code/SectionErrorCode.java
  src/main/java/servnow/servnow/domain/question/model/Question.java
  src/main/java/servnow/servnow/domain/section/repository/SectionRepository.java
Labels: ✨ feat, 진

#23 [feat/#16] 마이페이지 내 정보 수정 및 저장, 이메일 인증, 아아디 중복 구현
  build.gradle
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/dto/request/CertificationNumberRequest.java
  src/main/java/servnow/servnow/api/user/dto/request/EmailDuplicateRequest.java
  src/main/java/servnow/servnow/api/user/dto/request/SaveEditProfilePageRequest.java
  src/main/java/servnow/servnow/api/user/dto/request/SerialIdDuplicateRequest.java
  src/main/java/servnow/servnow/api/user/dto/response/EditProfilePageResponse.java
  src/main/java/servnow/servnow/api/user/dto/response/KakaoEditProfilePageResponse.java
  src/main/java/servnow/servnow/api/user/dto/response/MyPageResponse.java
  src/main/java/servnow/servnow/api/user/dto/response/ServnowEditProfilePageResponse.java
  src/main/java/servnow/servnow/api/user/service/EmailService.java
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/api/user/service/UserInfoFinder.java
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
  src/main/java/servnow/servnow/common/code/UserErrorCode.java
  src/main/java/servnow/servnow/common/code/UserInfoErrorCode.java
  src/main/java/servnow/servnow/domain/user/model/User.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
  src/main/java/servnow/servnow/domain/user/repository/UserInfoRepository.java
  src/main/java/servnow/servnow/domain/user/repository/UserRepository.java
Labels: ✨ feat, 🚧 dependency, 우현

#30 [fix/#28] 더티체킹 안되는 문제 fix
  src/main/java/servnow/servnow/api/survey/service/SurveyCommandService.java
  src/main/java/servnow/servnow/api/user/service/UserInfoFinder.java
  src/main/java/servnow/servnow/api/user/service/UserInfoUpdater.java
  src/main/java/servnow/servnow/common/code/UserInfoErrorCode.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
  src/main/java/servnow/servnow/domain/user/repository/UserInfoRepository.java
Labels: 🐞 fix, 진

#32 [feat/#31] 스웨거 셋팅
  build.gradle
  src/main/java/servnow/servnow/api/config/SwaggerConfig.java
Labels: ✨ feat, 진

#25 [feat/#15, #26] 카카오 로그인 API, 일반 로그인/회원가입 API 구현
  .gitignore
  build.gradle
  src/main/java/servnow/servnow/ServnowApplication.java
  src/main/java/servnow/servnow/api/auth/controller/AuthController.java
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
  src/main/java/servnow/servnow/api/auth/service/AuthService.java
  src/main/java/servnow/servnow/api/auth/service/CustomUserDetailService.java
  src/main/java/servnow/servnow/api/auth/service/KakaoService.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
  src/main/java/servnow/servnow/api/auth/service/UserUpdater.java
  src/main/java/servnow/servnow/api/dto/auth/AuthToken.java
  src/main/java/servnow/servnow/api/dto/login/UserJoinRequest.java
  src/main/java/servnow/servnow/api/dto/login/UserLoginRequest.java
  src/main/java/servnow/servnow/api/dto/login/UserLoginResponse.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/service/UserFinder.java
  src/main/java/servnow/servnow/auth/JwtAuthenticationEntryPoint.java
  src/main/java/servnow/servnow/auth/TmpClass.java
  src/main/java/servnow/servnow/auth/UserAuthentication.java
  src/main/java/servnow/servnow/auth/UserId.java
  src/main/java/servnow/servnow/auth/UserIdArgumentResolver.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/auth/config/WebClientConfig.java
  src/main/java/servnow/servnow/auth/filter/ExceptionHandlerFilter.java
  src/main/java/servnow/servnow/auth/filter/JwtAuthenticationFilter.java
  src/main/java/servnow/servnow/auth/jwt/JwtGenerator.java
  src/main/java/servnow/servnow/auth/jwt/JwtProvider.java
  src/main/java/servnow/servnow/auth/jwt/JwtValidator.java
  src/main/java/servnow/servnow/auth/jwt/Token.java
  src/main/java/servnow/servnow/common/code/AuthErrorCode.java
  src/main/java/servnow/servnow/common/code/LoginErrorCode.java
  src/main/java/servnow/servnow/domain/user/model/User.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
  src/main/java/servnow/servnow/domain/user/model/enums/Gender.java
  src/main/java/servnow/servnow/domain/user/repository/UserInfoRepository.java
  src/main/java/servnow/servnow/domain/user/repository/UserRepository.java
Labels: ✨ feat, 맨디

#29 [feat/#24] 내가 제작한 설문지 목록 조회(최신 순, 오래된 순, 참여자 순)
  src/main/java/servnow/servnow/api/result/dto/response/QuestionResult.java
  src/main/java/servnow/servnow/api/result/dto/response/SubjectiveResponse.java
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/dto/response/MySurveyResponse.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 우현

#33 [feat/#27] 내가 제작한 설문지 결과 조회
  src/main/java/servnow/servnow/api/result/dto/response/MySurveysResultResponse.java
  src/main/java/servnow/servnow/api/result/service/ResultQueryService.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/domain/multiplechoiceresult/model/MultipleChoiceResult.java
  src/main/java/servnow/servnow/domain/question/model/MultipleChoice.java
  src/main/java/servnow/servnow/domain/question/model/Question.java
  src/main/java/servnow/servnow/domain/subjectiveresult/model/SubjectiveResult.java
  src/main/java/servnow/servnow/domain/surveyresult/repository/SurveyResultRepository.java
Labels: ✨ feat, 우현

#34 [feat] Home API 구현 #20
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/response/HomeSurveyGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/common/code/SurveyErrorCode.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 쟌

#38 [feat] 설문 검색 API 구현 #35
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/response/SurveySearchGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 쟌

#40 [fix] jwt parsing 문제 해결
  src/main/java/servnow/servnow/api/auth/controller/FindController.java
  src/main/java/servnow/servnow/api/auth/service/FindInfoService.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/auth/filter/JwtAuthenticationFilter.java
  src/main/java/servnow/servnow/auth/jwt/JwtGenerator.java
  src/main/java/servnow/servnow/auth/jwt/JwtValidator.java
  src/main/java/servnow/servnow/domain/user/repository/UserInfoRepository.java
Labels: 🐞 fix, 맨디

#42 [fix/#41] PR#16, PR#27에서 누락된 UserController 코드 추가 및 @UserId 사용
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
Labels: 🐞 fix, 우현

#44 [feat] userId 관련 추가
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/response/SurveyIntroGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/auth/config/WebClientConfig.java
Labels: ✨ feat, 진

#45 [feat] 회원용/비회원용 화면 분리
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: ✨ feat, 진

#47 [feat] 유저 포인트 조회
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/dto/response/UserPointGetResponse.java
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
Labels: ✨ feat, 진

#50 [feat] 로그인 연결 #49
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: ✨ feat, 쟌

#36 [feat] 답변 제출 API 구현
  src/main/java/servnow/servnow/api/result/controller/ResultController.java
  src/main/java/servnow/servnow/api/result/dto/request/ResultPostRequest.java
  src/main/java/servnow/servnow/api/result/service/MultipleChoiceResultUpdater.java
  src/main/java/servnow/servnow/api/result/service/ResultCommandService.java
  src/main/java/servnow/servnow/api/result/service/ResultUpdater.java
  src/main/java/servnow/servnow/api/result/service/SubjectiveResultUpdater.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/common/code/MultipleChoiceErrorCode.java
  src/main/java/servnow/servnow/common/code/MultipleChoiceResultErrorCode.java
  src/main/java/servnow/servnow/common/code/QuestionErrorCode.java
  src/main/java/servnow/servnow/common/code/SubjectiveResultErrorCode.java
  src/main/java/servnow/servnow/common/code/SurveyResultErrorCode.java
  src/main/java/servnow/servnow/domain/multiplechoiceresult/model/MultipleChoiceResult.java
  src/main/java/servnow/servnow/domain/subjectiveresult/model/SubjectiveResult.java
  src/main/java/servnow/servnow/domain/surveyresult/model/SurveyResult.java
  src/main/java/servnow/servnow/domain/surveyresult/repository/SurveyResultRepository.java
Labels: ✨ feat, 주디

#52 [fix/#51] @Parameter (hidden=true) 설정
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: 🐞 fix, 우현

#53 [feat/#26] id/pw 찾기 api 구현
  src/main/java/servnow/servnow/api/auth/controller/FindController.java
  src/main/java/servnow/servnow/api/auth/service/FindInfoService.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
  src/main/java/servnow/servnow/api/dto/login/UserChangePwRequest.java
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/common/code/LoginErrorCode.java
  src/main/java/servnow/servnow/common/code/UserErrorCode.java
Labels: ✨ feat, 맨디

#57 [feat/#55] 토큰 재발급 구현
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
  src/main/java/servnow/servnow/api/auth/dto/response/ReissueTokenResponse.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: ✨ feat, 진

#59 [feat/#58] 로그아웃 구현
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
Labels: ✨ feat, 진

#60 [refac/#26] id 찾기/pw 변경 로직 수정
  src/main/java/servnow/servnow/api/auth/controller/FindController.java
Labels: ♻️ refac, 맨디

#62 [feat/#61] CORS 설정 추가
  src/main/java/servnow/servnow/api/config/CustomConfig.java
Labels: ✨ feat, 진

#64 [fix/#63] /api/v1/survey GET만 시큐리티 검증 안하도록 fix
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: 🐞 fix, 진

#65 [feat/#26] 회원가입 이메일 인증 api 구현
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
  src/main/java/servnow/servnow/api/auth/service/KakaoService.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
  src/main/java/servnow/servnow/api/dto/login/UserJoinRequest.java
  src/main/java/servnow/servnow/api/user/service/UserFinder.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
  src/main/java/servnow/servnow/common/code/LoginErrorCode.java
  src/main/java/servnow/servnow/domain/user/model/User.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
  src/main/java/servnow/servnow/domain/user/model/enums/Gender.java
Labels: ✨ feat, 맨디

#66 [fix/#26] 회원가입 - 생일 String 타입으로 변경
  src/main/java/servnow/servnow/api/auth/service/KakaoService.java
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
  src/main/java/servnow/servnow/api/dto/login/UserJoinRequest.java
  src/main/java/servnow/servnow/domain/user/model/UserInfo.java
Labels: 🐞 fix, 맨디

#67 [fix/#26] 회원가입 - 이메일 인증 request 변경
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
Labels: 🐞 fix, 맨디

#70 [feat/#26] 회원가입 아이디 중복 확인
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: ✨ feat, 맨디

#69 [feat/#68] 설문지 결과페이지 인사이트 메모장 작성/조회
  src/main/java/servnow/servnow/api/result/dto/request/MySurveysResultMemoRequest.java
  src/main/java/servnow/servnow/api/result/dto/response/MySurveysResultMemoResponse.java
  src/main/java/servnow/servnow/api/result/dto/response/QuestionResult.java
  src/main/java/servnow/servnow/api/result/dto/response/SubjectiveResponse.java
  src/main/java/servnow/servnow/api/result/service/ResultCommandService.java
  src/main/java/servnow/servnow/api/result/service/ResultQueryService.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/common/code/SurveyResultErrorCode.java
  src/main/java/servnow/servnow/domain/question/model/Question.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
  src/main/java/servnow/servnow/domain/surveyresult/repository/SurveyResultRepository.java
  src/main/java/servnow/servnow/domain/surveyresultmemo/model/SurveyResultMemo.java
  src/main/java/servnow/servnow/domain/surveyresultmemo/repository/SurveyResultMemoRepository.java
Labels: ✨ feat, 우현

#73 [fix/#72] 로그아웃 안되는 문제 fix
  src/main/java/servnow/servnow/auth/config/SecurityConfig.java
Labels: 🐞 fix, 진

#74 [feat] 홈화면, 설문 검색 회원/비회원 구분 #71
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/auth/UserIdArgumentResolver.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 쟌

#75 [refac/#26] 회원가입 아이디 중복 변경
  src/main/java/servnow/servnow/api/auth/controller/LoginController.java
Labels: ♻️ refac, 맨디

#77 [fix] 홈화면, 설문 검색 Response 포맷 수정 #76
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/dto/response/HomeSurveyListGetResponse.java
  src/main/java/servnow/servnow/api/survey/dto/response/SurveySearchGetResponse.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
Labels: 🐞 fix, 쟌

#79 [feat/#78] USER_INFO_NOT_FOUND 에러 추가
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
  src/main/java/servnow/servnow/common/code/UserErrorCode.java
Labels: 🔥 hotfix, 우현

#80 [hotfix/#78] userInfoRepository에서 유저 조회에 사용하는 jpa 함수 변경
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
Labels: 🔥 hotfix, 우현

#81 Feat/#78
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/api/user/service/UserQueryService.java
  src/main/java/servnow/servnow/common/code/UserErrorCode.java
  src/main/java/servnow/servnow/common/code/UserInfoErrorCode.java
Labels: 🔥 hotfix, 우현

#86 [feat/#83] 메모장 조회에 메모별 id값 추가
  src/main/java/servnow/servnow/api/result/dto/response/MySurveysResultMemoResponse.java
  src/main/java/servnow/servnow/api/result/service/ResultQueryService.java
Labels: ✨ feat, 우현

#87 [fix/#26] 회원가입 기본 이미지 경로 설정
  src/main/java/servnow/servnow/api/auth/service/LoginService.java
Labels: 맨디

#92 [fix/#91] 마이페이지 내가 제작한 설문지 결과 수정 #91
  src/main/java/servnow/servnow/api/result/dto/response/MySurveysResultResponse.java
  src/main/java/servnow/servnow/api/result/service/ResultQueryService.java
Labels: 🐞 fix, 우현

#95 [feat/#93] 메모 삭제 API 구현
  src/main/java/servnow/servnow/api/result/service/ResultCommandService.java
  src/main/java/servnow/servnow/api/result/service/surveyresultmemo/SurveyResultMemoFinder.java
  src/main/java/servnow/servnow/api/result/service/surveyresultmemo/SurveyResultMemoUpdater.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/common/code/SurveyResultMemoErrorCode.java
Labels: ✨ feat, 진

#96 [feat/#94] 메모 수정 API 구현
  src/main/java/servnow/servnow/api/result/dto/request/SurveyResultMemosPatchRequest.java
  src/main/java/servnow/servnow/api/result/service/ResultCommandService.java
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/domain/surveyresultmemo/model/SurveyResultMemo.java
Labels: ✨ feat, 진

#100 [feat] 설문 검색 다중 키워드 허용 #97
  src/main/java/servnow/servnow/api/survey/controller/SurveyController.java
  src/main/java/servnow/servnow/api/survey/service/SurveyFinder.java
  src/main/java/servnow/servnow/api/survey/service/SurveyQueryService.java
  src/main/java/servnow/servnow/domain/survey/repository/SurveyRepository.java
Labels: ✨ feat, 쟌

#102 [feat/#101] 마이페이지 프로필 사진 업로드
  build.gradle
  src/main/java/servnow/servnow/api/user/controller/UserController.java
  src/main/java/servnow/servnow/api/user/dto/request/SaveEditProfilePageRequest.java
  src/main/java/servnow/servnow/api/user/dto/request/UpdateProfileUrlRequest.java
  src/main/java/servnow/servnow/api/user/service/UserCommandService.java
  src/main/java/servnow/servnow/domain/config/S3Config.java
  src/main/java/servnow/servnow/domain/s3/S3Manager.java
  src/main/java/servnow/servnow/domain/s3/uuid/model/Uuid.java
  src/main/java/servnow/servnow/domain/s3/uuid/repository/UuidRepository.java
Labels: ✨ feat, 우현
